import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import { ThemeProvider } from "@/provider/ThemeProvider";
import { Toaster } from "sonner";
import Header from "@/components/general/Header";

export const metadata: Metadata = {
  title: "Silver Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen w-full flex-col">
              <Header />
              <main className="flex flex-1 flex-col px-4 pt-10 xl:px-8">
                {children}
              </main>
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
